import 'package:flutter/material.dart';

const persian_blue = Color(0xFF1947E6);
const white = Color(0xFFFFFFFF);
const athens_gray = Color(0xFFF4F5F7);
const lightening_yellow = Color(0xFFFFBD12);
const flamingo = Color(0xFFF95A2C);
const black = Color(0xFF000000);
const wood_smoke = Color(0xFF18191F);
const trout = Color(0xFF474A57);
const santas_gray = Color(0xFF969BAB);
const selago = Color(0xFFE9E7FC);
const carribean_green = Color(0xFF00C6AE);
const santas_gray_10 = Color(0xFF9FA4B4);
const dandelion = Color(0xFFFFD465);
const caribbean_color = Color(0xFF00C6AE);
const pastel_pink = Color(0xFFFFC7DE);
const pink_salomn = Color(0xFFFF89BB);
const athen_gray = Color(0xFFF4F5F7);
const bareley_white = Color(0xFFFFF4CC);
const fair_pink = Color(0xFFFFE8E8);
const foam = Color(0xFFD6FCF7);
const lavandar_bush = Color(0xFFFFF3F8);
const mona_lisa = Color(0xFFFF9692);
const athens = Color(0xFFEEEFF4);
const turquoise_blue = Color(0xFF61E4C5);
